version: "3"
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password

  frontend:
    image: cthit/gamma-frontend:development
    network_mode: host
    ports:
      - 3000:3000

  backend:
    image: cthit/gamma-backend
    environment:
      # Default admin user name = admin
      # Default admin password  = password

      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres

      REDIS_HOST: redis
      REDIS_PASSWORD: ""

      GOTIFY_KEY: "123abc"
      GOTIFY_URL: http://gotify:8080/mail

      SERVER_PORT: 8081
      FRONTEND_REDIRECT_URI: http://localhost:3000/login
      SUCCESSFUL_LOGIN: http://localhost:3000
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      COOKIE_DOMAIN: localhost

    ports:
      - 8081:8081

  redis:
    image: redis:5.0

  gotify:
    image: cthit/gotify
    environment:
      GOTIFY_PRE-SHARED-KEY: 123abc
      GOTIFY_MOCK-MODE: "true"
