volumes:
  postgres-data:

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    container_name: db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:5.0
    restart: always

  gotify:
    container_name: gotify
    image: cthit/gotify:latest
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abc"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_DEBUG-MODE: "true"
