volumes:
  postgres-data:

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"

  gotify:
    image: cthit/gotify:latest
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abc"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_DEBUG-MODE: "true"
    ports:
      - "80:80"