name: E2E Tests

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3

      - name: Install dependencies
        run: cd e2e && pnpm install

      - name: Install Playwright Browsers
        run: cd e2e && pnpm exec playwright install --with-deps chromium

      - name: Determine Gamma version
        id: gamma-version
        run: |
          SHA="${{ github.event.workflow_run.head_sha }}"
          echo "version=sha-${SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Run E2E tests
        run: make test-e2e GAMMA_VERSION=${{ steps.gamma-version.outputs.version }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
